### PR TITLE
Run integration tests after unit tests

### PR DESCRIPTION
**Pull request by arturo-seijas**
Trigger integration test also after unit test execution. Will be kept only if the docker registry can be accessed from a PR from a fork.

### CODE REVIEW

**Review by mthaddon — APPROVED** [review]
LGTM

**Comment by weiiwang01** [comment]
I am a little confused about this, isn't the integration tests and unit tests both triggered by pull requests?

**Comment by arturo-seijas** [comment]
> I am a little confused about this, isn't the integration tests and unit tests both triggered by pull requests?

I'm not surprised.
I need to merge this in order to test if the docker repository will work with PRs comming from forks.

**Comment by weiiwang01** [comment]
> > I am a little confused about this, isn't the integration tests and unit tests both triggered by pull requests?
> 
> I'm not surprised. I need to merge this in order to test if the docker repository will work with PRs comming from forks.

Gotcha, just if you trigger the integration test using a `workflow_run` event, the integration tests will not be shown up as checks in the PR, just like the comment workflow never shows up in the PR checks. If that's okay, I will approve that.

**Review by gtrkiller — APPROVED** [review]
LGTM

**Comment by arturo-seijas** [comment]
> > > I am a little confused about this, isn't the integration tests and unit tests both triggered by pull requests?
> > 
> > 
> > I'm not surprised. I need to merge this in order to test if the docker repository will work with PRs comming from forks.
> 
> Gotcha, just if you trigger the integration test using a `workflow_run` event, the integration tests will not be shown up as checks in the PR, just like the comment workflow never shows up in the PR checks. If that's okay, I will approve that.

Indeed, I had not considered this. I'll try to come up with another approach.
Thank you very much

**Pull request closed without merging**
