### PR TITLE
Configure bandit in pyproject.toml instead of using .bandit file

### LINKED ISSUE #141: Configure bandit in pyproject.toml instead of using separate .bandit config file.
### Enhancement Proposal

Configuration of [bandit](https://github.com/PyCQA/bandit/) could be done in `pyproject.toml` as per https://bandit.readthedocs.io/en/latest/config.html. This would be cleaner as we already use a `pyproject.toml` in our charm repos and we don't need to support an additional config file (`.bandit` at top of repo).

### PR DESCRIPTION
**Pull request by arturo-seijas**
Closes #141

### CODE REVIEW

**Review by merkata — COMMENTED** [review]
Nice, did the changes work locally? I remember I had issues with configuring bandit, but that could've been just me.

**Comment by arturo-seijas** [comment]
> Nice, did the changes work locally? I remember I had issues with configuring bandit, but that could've been just me.

Yes, I just had to install toml to make it work

**Review by weiiwang01 — APPROVED** [review]
LGTM, thanks!

**Review by mthaddon — APPROVED** [review]
LGTM, thx

**Review by merkata — COMMENTED** [review]
Awesome, approving!

**Comment by jdkandersson** [comment]
Nice!

**Pull request merged**
