### PR TITLE
Migrate from ingress to nginx-route relation

### PR DESCRIPTION
**Pull request by weiiwang01**
### Overview

This pull request transitions the Indico charm from the now-deprecated `ingress` relation to the updated `nginx-route` relation.

Upon the release of this revision, use the steps below to upgrade the charm. Please be aware that this upgrade will result in a brief downtime, as the ingress will be temporarily removed from the cluster.

```bash
juju remove-relation indico:ingress nginx-ingress-integrator
juju refresh indico
juju relate indico:nginx-route nginx-ingress-integrator
```

### Rationale

The `ingress` relation the charm currently uses is now deprecated.

### Library Changes

Remove `charms.nginx_ingress_integrator.v0.ingress`, add `charms.nginx_ingress_integrator.v0.nginx_route`.

### Checklist

- [x] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [x] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [ ] The changes are compliant with [ISD054 - Manging Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [ ] The documentation is generated using `src-docs`
- [ ] The documentation for charmhub is updated
- [x] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)

For item 3 and item 4, they haven't be initialized in the indico charm, and there is no need to change the document for this update.

### CODE REVIEW

**Review by arturo-seijas — DISMISSED** [review]
LGTM

**Review by merkata — DISMISSED** [review]

**Review by arturo-seijas — APPROVED** [review]
LGTM

**Comment by jdkandersson** [comment]
Please ensure that this PR complies with the spec on pull request creation (ISD062) - it should not be merged before then

**Review by jdkandersson — CHANGES_REQUESTED** [review]
Thanks for submitting the PR, please ensure that it complies with ISD062 on pull request creation

**Comment by weiiwang01** [comment]
> Thanks for submitting the PR, please ensure that it complies with ISD062 on pull request creation

Updated, thanks!

**Comment by jdkandersson** [comment]
> > Thanks for submitting the PR, please ensure that it complies with ISD062 on pull request creation
> 
> Updated, thanks!

Thanks, please include an explanation for the unchecked items on the checklist as well 🙂

**Comment by weiiwang01** [comment]
> > Thanks for submitting the PR, please ensure that it complies with ISD062 on pull request creation
> 
> Updated, thanks!

I also updated the description to explain the unchecked items on the checklist.

**Review by jdkandersson — APPROVED** [review]

**Pull request merged**
