### PR TITLE
Use SAML groups identity provider

### PR DESCRIPTION
**Pull request by cbartz**
Use the identity provider from the [Flask-Multipass-SAML-Groups](https://github.com/canonical/flask-multipass-saml-groups) plugin if it has been configured.

### CODE REVIEW

**Review by arturo-seijas — APPROVED** [review]
LGTM

**Review by mthaddon — APPROVED** [review]
Change looks good. There seem to be two unrelated test failures here, need to confirm if it's expected that a change to the docs proposed in a PR would fail tests (i.e. changes need to be applied before landing?), and I see a branch from Arturo in progress to address SAML integration test failures, but I'm not sure it's the same issue as what you're seeing here...

**Comment by arturo-seijas** [comment]
> Change looks good. There seem to be two unrelated test failures here, need to confirm if it's expected that a change to the docs proposed in a PR would fail tests (i.e. changes need to be applied before landing?), and I see a branch from Arturo in progress to address SAML integration test failures, but I'm not sure it's the same issue as what you're seeing here...

Let's retry. The runner run out of disk

**Comment by cbartz** [comment]
> Change looks good. There seem to be two unrelated test failures here, need to confirm if it's expected that a change to the docs proposed in a PR would fail tests (i.e. changes need to be applied before landing?), and I see a branch from Arturo in progress to address SAML integration test failures, but I'm not sure it's the same issue as what you're seeing here...

There was a diff in the base of `docs/reference/plugins.md` and the discourse post because the discourse post had no trailing newline and the source did. I fixed it by recreating the `upload-charm-docs/base-content` tag and updating the discussion post.

**Pull request merged**
