### PR TITLE
Adjust memberOf casing to fix group membership (#236)

### PR DESCRIPTION
**Pull request by jdkandersson**
Re-created this PR to enable tests to run with secrets: https://github.com/canonical/indico-operator/pull/236

Improvements on parallelization for integration test: parallel deployment of dependencies and building of the charm

### CODE REVIEW

**Comment by jdkandersson** [comment]
Looks like there is the juju compatibility problem on this PR as well

**Review by arturo-seijas — DISMISSED** [review]
LGTM

**Review by nrobinaubertin — DISMISSED** [review]

**Review by mthaddon — DISMISSED** [review]

**Comment by jdkandersson** [comment]
Do we have any indication why the timeout is happening?

Maybe for the approval to skip we could have a screenshot with the integration tests passing locally including the git commit hash that is up for approval?

**Comment by arturo-seijas** [comment]
> Do we have any indication why the timeout is happening?
> 
> Maybe for the approval to skip the integration test we could have a screenshot with the integration tests passing locally including the git commit hash that is up for approval? I'll write a proposal in the contributing guide we can look at: [canonical/is-charms-contributing-guide#53](https://github.com/canonical/is-charms-contributing-guide/pull/53)

We don't, but by the time it times out two integration tests have passed. Merging the PR with the checks failed won't help because the tests will timeout again on merge. We'd need to disable them.

**Comment by jdkandersson** [comment]
> > Do we have any indication why the timeout is happening?
> > Maybe for the approval to skip the integration test we could have a screenshot with the integration tests passing locally including the git commit hash that is up for approval? I'll write a proposal in the contributing guide we can look at: [canonical/is-charms-contributing-guide#53](https://github.com/canonical/is-charms-contributing-guide/pull/53)
> 
> We don't, but by the time it times out two integration tests have passed. Merging the PR with the checks failed won't help because the tests will timeout again on merge. We'd need to disable them.

Is it possible to disable the integration tests from this repo? Or would it require changes on `operator-workflows`?

**Review by yanksyoon — APPROVED** [review]
LGTM!

**Review by yanksyoon — DISMISSED** [review]

**Review by yanksyoon — APPROVED** [review]

**Review by mthaddon — APPROVED** [review]

**Comment by jdkandersson** [comment]
Looks like we got the integration tests fixed 💪

**Pull request merged**
