### PR TITLE
Remove request size limit

### PR DESCRIPTION
**Pull request by arturo-seijas**
Remove requestion size limit by changing nginx `client_max_body_size` config. It defaults to 1mb

### CODE REVIEW

**Review by weiiwang01 — DISMISSED** [review]
The inclusive naming check failed, can you update the .woke.yaml to exclude that?

**Review by mthaddon — COMMENTED** [review]
LGTM

**Review by mthaddon — APPROVED** [review]

**Review by weiiwang01 — APPROVED** [review]

**Comment by jdkandersson** [comment]
I realise this is merged, @arturo-seijas  it seems the integration tests are failing?

**Comment by arturo-seijas** [comment]
> I realise this is merged, @arturo-seijas it seems the integration tests are failing?

Nope, they are passing https://github.com/canonical/indico-operator/actions

**Pull request merged**
